- tmadminCommand: tmadmin -r
  domainName: domain1
  envVariables:
    - name: TUXCONFIG
      value: /path/to/domain1/TUXCONFIG/file

- tmadminCommand: tmadmin -r
  domainName: domain2
  envVariables:
    - name: TUXCONFIG
      value: /path/to/domain2/TUXCONFIG/file